import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, Divider, IconButton, LinearProgress, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { Add, AutoAwesome, CheckCircle, CloudUpload, Code, ContentCopy, DragIndicator, Extension, FilterList, Lock, MoreHoriz, PlayArrow, Save, Search, Security, Timeline, Tune, Web } from "@mui/icons-material";

const meta = { title: "Platform/Advanced", parameters: { layout: "fullscreen" } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
const Stage=({children}:{children:React.ReactNode})=><Box minHeight="100vh" p={{xs:2,md:5}} bgcolor="background.default"><Box maxWidth={1280} mx="auto">{children}</Box></Box>;

export const StoryboardCanvas: Story={render:()=> <Stage><Stack spacing={2}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h2">Storyboard canvas</Typography><Typography color="text.secondary">Compose the experience as a sequence of validated scenes.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<Save/>}>Save</Button><Button variant="accent">Preview</Button></Stack></Stack><Card><CardContent><Stack direction="row" spacing={1} overflow="auto" pb={1}>{Array.from({length:8},(_,i)=><Paper key={i} variant="outlined" sx={{minWidth:170,p:1.2,borderColor:i===2?"primary.main":"divider"}}><Stack direction="row" justifyContent="space-between"><Chip size="small" label={String(i+1).padStart(2,"0")}/><DragIndicator fontSize="small"/></Stack><Box height={95} mt={1} borderRadius={2} sx={{background:["linear-gradient(135deg,#3b2c3d,#c99da8)","linear-gradient(135deg,#1e2c3b,#839eb5)","linear-gradient(135deg,#75472d,#dfa06a)","linear-gradient(135deg,#26372e,#9ba37b)"][i%4]}}/><Typography fontWeight={750} mt={1}>Scene {i+1}</Typography><Typography variant="caption" color="text.secondary">{i%3===0?"Hero":"Interactive"} · {i+1} assets</Typography></Paper>)}</Stack></CardContent></Card></Stack></Stage>};

export const VisualRecipeBuilder: Story={render:()=> <Stage><Grid><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h2">Visual recipe</Typography><Typography color="text.secondary">Define typography, color, surfaces, motion and composition as structured tokens.</Typography></Box><Button variant="accent">Save recipe</Button></Stack><Tabs value={0} sx={{mt:2}}><Tab label="Style"/><Tab label="Typography"/><Tab label="Motion"/><Tab label="Composition"/></Tabs><Stack spacing={2} mt={3}><TextField label="Recipe name" value="Midnight Cinema" slotProps={{input:{readOnly:true}}}/><Stack direction="row" spacing={1}><Paper sx={{width:72,height:72,bgcolor:"#211f1c"}}/><Paper sx={{width:72,height:72,bgcolor:"#7057e8"}}/><Paper sx={{width:72,height:72,bgcolor:"#f6f5f2"}}/><Paper sx={{width:72,height:72,bgcolor:"#ffffff"}}/></Stack><Stack direction="row" spacing={1}><Chip label="Editorial"/><Chip label="Cinematic"/><Chip label="Minimal"/></Stack></Stack></CardContent></Card></Grid></Stage>};

export const InteractionBuilder: Story={render:()=> <Stage><Stack spacing={2}><Card><CardContent><Typography variant="h2">Interaction builder</Typography><Typography color="text.secondary">Configure guest actions without embedding arbitrary application code.</Typography><Stack spacing={1.25} mt={3}>{["RSVP","Quiz branching","Guestbook","Voting","Media submission","Contact form"].map((x,i)=><Paper key={x} variant="outlined" sx={{p:1.5}}><Stack direction="row" alignItems="center" spacing={1.5}><Extension color="primary"/><Box flex={1}><Typography fontWeight={750}>{x}</Typography><Typography variant="caption" color="text.secondary">Schema validated interaction</Typography></Box><Chip label={i<4?"Configured":"Available"} size="small" color={i<4?"success":"default"}/><Button size="small" variant="outlined">Configure</Button></Stack></Paper>)}</Stack></CardContent></Card></Stack></Stage>};

export const AutomationCenter: Story={render:()=> <Stage><Grid><Card><CardContent><Typography variant="h2">Automation center</Typography><Typography color="text.secondary">Connect publishing, notifications and guest workflows.</Typography><Stack spacing={1.5} mt={3}>{["Publish → notify owner","RSVP → confirmation email","Guest submission → moderation queue","Campaign → scheduled delivery"].map((x,i)=><Paper key={x} variant="outlined" sx={{p:1.5}}><Stack direction="row" alignItems="center" spacing={1.5}><Timeline color="primary"/><Box flex={1}><Typography fontWeight={750}>{x}</Typography><Typography variant="caption" color="text.secondary">Trigger · action · audit log</Typography></Box><Chip label={i<3?"Active":"Draft"} color={i<3?"success":"primary"} size="small"/><IconButton><MoreHoriz/></IconButton></Stack></Paper>)}</Stack></CardContent></Card></Grid></Stage>};

export const DeveloperExport: Story={render:()=> <Stage><Stack spacing={2}><Card><CardContent><Stack direction="row" spacing={1.5} alignItems="center"><Code color="primary"/><Box><Typography variant="h2">Developer export</Typography><Typography color="text.secondary">Export a validated ExperienceSpec and immutable build metadata.</Typography></Box></Stack><Divider sx={{my:2}}/><Paper sx={{p:2,bgcolor:"#211f1c",color:"#fff",fontFamily:"monospace",overflow:"auto"}}><Typography component="pre" fontSize={11}>{`{
  "version": 7,
  "schema": "experience/v1",
  "scenes": 7,
  "interactions": ["rsvp", "quiz"],
  "artifact": "immutable",
  "publicUrl": "elena-victor.invite.md"
}`}</Typography></Paper><Stack direction="row" spacing={1} mt={2}><Button variant="accent" startIcon={<ContentCopy/>}>Copy JSON</Button><Button variant="outlined">Download package</Button></Stack></CardContent></Card></Stack></Stage>};

export const SecurityCenter: Story={render:()=> <Stage><Grid><Card><CardContent><Stack direction="row" spacing={1.5}><Security color="primary"/><Box><Typography variant="h2">Security & privacy</Typography><Typography color="text.secondary">Review access, public exposure and audit events.</Typography></Box></Stack><Stack spacing={1.25} mt={3}>{["2FA enabled","3 workspace members","1 custom domain","Public guest submissions require moderation","Published artifacts are immutable"].map(x=><Paper key={x} variant="outlined" sx={{p:1.5}}><Stack direction="row" spacing={1.5} alignItems="center"><CheckCircle color="success"/><Typography fontWeight={700}>{x}</Typography></Stack></Paper>)}</Stack></CardContent></Card></Grid></Stage>};

export const PerformanceCenter: Story={render:()=> <Stage><Grid><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h2">Delivery performance</Typography><Typography color="text.secondary">Public runtime health and media optimization.</Typography></Box><Chip label="Healthy" color="success"/></Stack><Stack spacing={2} mt={3}>{[["LCP","1.4s",88],["INP","92ms",94],["CLS","0.02",98],["Media cache hit","96%",96]].map(([label,value,score])=><Box key={String(label)}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{label}</Typography><Typography>{value}</Typography></Stack><LinearProgress variant="determinate" value={Number(score)} sx={{mt:.6}}/></Box>)}</Stack></CardContent></Card></Grid></Stage>};

export const MarketplaceCreator: Story={render:()=> <Stage><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h2">Marketplace creator</Typography><Typography color="text.secondary">Package a visual recipe or interaction for other creators.</Typography></Box><Button variant="accent" startIcon={<Web/>}>Submit pack</Button></Stack><Stack direction="row" spacing={1} my={3}><Chip label="Visual recipe" color="primary"/><Chip label="Component pack"/><Chip label="Interaction"/></Stack><TextField fullWidth label="Pack name" value="Midnight Cinema" slotProps={{input:{readOnly:true}}}/><Stack direction="row" spacing={1.5} mt={2}><Paper variant="outlined" sx={{p:2,flex:1}}><Typography fontWeight={800}>Assets</Typography><Typography variant="body2" color="text.secondary">14 components · 6 tokens</Typography></Paper><Paper variant="outlined" sx={{p:2,flex:1}}><Typography fontWeight={800}>Validation</Typography><Typography variant="body2" color="text.secondary">Accessibility · schema · license</Typography></Paper></Stack></CardContent></Card></Stage>};

function Grid({children}:{children:React.ReactNode}) { return <Box display="grid" gap={2} sx={{gridTemplateColumns:{xs:"1fr",md:"minmax(0,1fr) minmax(280px,380px)"}}}>{children}</Box>; }
