import type { ExperienceSpec } from "@invite/invitation-schema";

export const sampleExperience: ExperienceSpec = {
  schemaVersion: "1.0",
  id: "date-surprise" as ExperienceSpec["id"],
  invitationId: "invitation-demo",
  visualLanguage: "cinematic",
  design: {
    theme: {
      background: "#fffaf3",
      surface: "#ffffff",
      text: "#241f1b",
      mutedText: "#756c64",
      primary: "#6f4b63",
      secondary: "#a97891",
      accent: "#d7a85b",
      border: "#ded5cd",
      headingFont: "Georgia, serif",
      bodyFont: "system-ui, sans-serif",
    },
    motion: "moderate",
  },
  scenes: [
    {
      id: "opening" as ExperienceSpec["scenes"][number]["id"],
      order: 0,
      purpose: "Opening",
      trigger: { type: "load" },
      content: {},
      components: [{ kind: "hero", content: { eyebrow: "September 28", title: "A little surprise", description: "Something cinematic, playful and personal is waiting for you." } }],
      mediaIds: [],
      interactionIds: [],
    },
    {
      id: "memory" as ExperienceSpec["scenes"][number]["id"],
      order: 1,
      purpose: "Story",
      trigger: { type: "after", seconds: 8 },
      content: {},
      components: [{ kind: "text", content: { title: "One more memory", body: "A short story beat belongs here. The creator can replace this with a validated memory and media selection." } }],
      mediaIds: [],
      interactionIds: [],
    },
    {
      id: "question" as ExperienceSpec["scenes"][number]["id"],
      order: 2,
      purpose: "Interaction",
      trigger: { type: "load" },
      content: {},
      components: [{ kind: "quiz", content: { question: "Where should the evening begin?", choices: ["At sunset", "After dark", "Somewhere unexpected"] } }],
      mediaIds: [],
      interactionIds: ["mood-quiz"],
    },
    {
      id: "reveal" as ExperienceSpec["scenes"][number]["id"],
      order: 3,
      purpose: "Reveal",
      trigger: { type: "interaction-complete", interactionId: "mood-quiz" },
      content: {},
      components: [{ kind: "reveal", content: { prompt: "Ready for the reveal?", title: "Valea Morilor", message: "Sunset. September 28. The rest is for us to discover." } }],
      mediaIds: [],
      interactionIds: [],
    },
  ],
  interactions: [{ type: "quiz", id: "mood-quiz", choices: ["At sunset", "After dark", "Somewhere unexpected"] }],
  variables: [],
};
